### ISSUE TITLE
DIO security

### ISSUE THREAD

**Issue by renanyoy** [ivoleitao/shadertoy#16]
**Describe the bug**
    Package dio is affected by security advisories. See https://dart.dev//go/pub-security-advisories

    - "dio vulnerable to CRLF injection with HTTP method string"
      Affects: 4.0.6
      https://github.com/advisories/GHSA-9324-jv53-9cc8
    - "Duplicate Advisory: Improper Neutralization of CRLF Sequences in dio"
      Affects: 4.0.6
      https://github.com/advisories/GHSA-jwpw-q68h-r678

**fix**
dart pub upgrade missing, shadertoy_client  still in 2.3.0
https://pub.dev/packages/shadertoy_client

**Comment by ivoleitao** [comment]
Hi, thanks for your issue. I'm currently doing heavy rework on this library (non api breaking). I can provide an intermediate version where all of that is already sorted out as Im using the newest versions of all the packages
